name: Deploy ML API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 703671921554.dkr.ecr.eu-west-1.amazonaws.com/titanic-app

      - name: Build and push Docker image
        run: |
          docker build -t titanic-app .
          docker tag titanic-app:latest 703671921554.dkr.ecr.eu-west-1.amazonaws.com/titanic-app:latest
          docker push 703671921554.dkr.ecr.eu-west-1.amazonaws.com/titanic-app:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster DevCluster --service titanic-app --force-new-deployment
